version: '3'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/news?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 050999

  mysql-db:
    image: mysql/mysql-server:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: news
      MYSQL_ROOT_PASSWORD: 050999
      MYSQL_USER: hungpt6
      MYSQL_PASSWORD: 050999
      MYSQL_ROOT_HOST: '%'
#    volumes:
#      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: 050999
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql-db:3306/news?allowPublicKeyRetrieval=true&useSSL=false -schemas=news -user=root -password=050999 -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - mysql-db